### ISSUE TITLE
Travis-CI configuration

### ISSUE THREAD

**Issue by fisharebest** [Stolz/Assets#73]
Your travis builds are failing.  e.g. https://travis-ci.org/Stolz/Assets/jobs/71597144

1) There is a message asking you to upgrade to the infrastructure.  You should do this.  It is much faster.  Just add the line `sudo: false` to your `.travis.yml`.

2) Your `.travis.yml` fetches/installs `composer`.  This is not necessary.  Composer is already installed, and will be run automatically if a `composer.json` exists.

This is the config I use in my PHP projects

```yml
language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
sudo: false
```
